namespace Blazor.AdminLte
{
    public enum Color
    {
        [Style("")]
        Default,
        [Style("danger")]
        Danger,
        [Style("warning")]
        Warning,
        [Style("primary")]
        Primary,
        [Style("secondary")]
        Secondary,
        [Style("info")]
        Info,
        [Style("success")]
        Success,
        [Style("black")]
        Black,
        [Style("gray-dark")]
        GrayDark,
        [Style("gray")]
        Gray,
        [Style("light")]
        Light,
        [Style("indigo")]
        Indigo,
        [Style("navy")]
        Navy,
        [Style("purple")]
        Purple,
        [Style("fuchsia")]
        Fuchsia,
        [Style("pink")]
        Pink,
        [Style("maroon")]
        Maroon,
        [Style("orange")]
        Orange,
        [Style("lime")]
        Lime,
        [Style("teal")]
        Teal,
        [Style("olive")]
        Olive,
        [Style("white")]
        White
    }
}
